spring:
  data:
    redis:
      host: localhost
      port: 6379

keycloak:
  auth-server-url: http://localhost:8180/auth

logging:
  level:
    root: INFO
    com.authservice: DEBUG

management:
  endpoint:
    health:
      show-details: always
